# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledgers.Account')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('line_dump', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=512)),
                ('additional', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=19, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banktransactions', to='bank_accounts.BankAccount')),
                ('tags', models.ManyToManyField(blank=True, default=None, related_name='banktransactions', to='ledgers.Tag')),
                ('transaction', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banktransactions', to='ledgers.Transaction')),
            ],
        ),
    ]
