# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankTransaction',
            new_name='BankLine',
        ),
        migrations.RenameField(
            model_name='bankentry',
            old_name='bank_transaction',
            new_name='bank_line',
        ),
        migrations.AddField(
            model_name='bankentry',
            name='subledger',
            field=models.CharField(blank=True, choices=[('sales', 'Sale'), ('bank_reconciliations', 'Bank Reconciliation'), ('expenses', 'Expense'), ('wages', 'Payroll'), ('creditors', 'Creditor'), ('journals', 'Journal')], default='', max_length=50),
        ),
    ]
