# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliations', '0002_auto_20171019_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankentry',
            old_name='bank_transaction',
            new_name='bank_line',
        ),
        migrations.AddField(
            model_name='bankentry',
            name='subledger',
            field=models.CharField(blank=True, choices=[('creditors', 'Creditor'), ('expenses', 'Expense'), ('sales', 'Sale'), ('journals', 'Journal'), ('bank_reconciliations', 'Bank Reconciliation')], default='', max_length=50),
        ),
    ]
