# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliations', '0003_auto_20171024_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankentry',
            name='subledger',
            field=models.CharField(blank=True, choices=[('sales', 'Sale'), ('creditors', 'Creditor'), ('expenses', 'Expense'), ('bank_reconciliations', 'Bank Reconciliation'), ('wages', 'Payroll'), ('journals', 'Journal')], default='', max_length=50),
        ),
    ]
