# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliations', '0004_auto_20171025_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankentry',
            name='subledger',
            field=models.CharField(blank=True, choices=[('expenses', 'Expense'), ('journals', 'Journal'), ('creditors', 'Creditor'), ('bank_reconciliations', 'Bank Reconciliation'), ('wages', 'Payroll'), ('sales', 'Sale')], default='', max_length=50),
        ),
    ]
