# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliations', '0005_auto_20171025_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankentry',
            name='subledger',
            field=models.CharField(blank=True, choices=[('journals', 'Journal'), ('wages', 'Payroll'), ('creditors', 'Creditor'), ('sales', 'Sale'), ('expenses', 'Expense'), ('bank_reconciliations', 'Bank Reconciliation')], default='', max_length=50),
        ),
    ]
