# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('ledgers', '0002_auto_20170629_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('entity', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledgers.Transaction')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
            },
        ),
    ]
