# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledgers.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
