# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:41
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('ledgers', '0001_initial'),
        ('bank_reconciliations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.IntegerField(default=14)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='entities.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditorInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('due_date', models.DateField(null=True)),
                ('invoice_number', models.CharField(max_length=128)),
                ('order_number', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('gst_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.Creditor')),
                ('transaction', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ledgers.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_entry', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_reconciliations.BankEntry')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.Creditor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
