# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 03:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creditors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='invoices',
            field=models.ManyToManyField(to='creditors.CreditorInvoice'),
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='note',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='reference',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
            preserve_default=False,
        ),
    ]
