# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditors', '0002_auto_20171021_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creditorinvoice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
