# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditors', '0003_auto_20171023_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, unique=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.Creditor')),
            ],
        ),
    ]
