# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditors', '0004_creditorlearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='entities.Entity', unique=True),
        ),
    ]
