# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 21:07
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditors', '0005_auto_20171024_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditor',
            options={'ordering': ['entity__name']},
        ),
        migrations.RemoveField(
            model_name='creditorpayment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='creditorpayment',
            name='value',
        ),
        migrations.AddField(
            model_name='creditorinvoice',
            name='unpaid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='creditorpayment',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
