# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliations', '0004_auto_20171025_0104'),
        ('creditors', '0006_auto_20171024_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('bank_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_reconciliations.BankEntry')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.Creditor')),
            ],
        ),
        migrations.CreateModel(
            name='CreditorPaymentInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.CreditorInvoice')),
            ],
        ),
        migrations.AlterField(
            model_name='creditorpayment',
            name='invoices',
            field=models.ManyToManyField(through='creditors.CreditorPaymentInvoices', to='creditors.CreditorInvoice'),
        ),
        migrations.AddField(
            model_name='creditorpaymentinvoices',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.CreditorPayment'),
        ),
    ]
