# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='account',
            name='special_account',
            field=models.CharField(blank=True, choices=[('ACP', 'Accounts Payable Liability Account'), ('ACR', 'Accounts Receivable Asset Account'), ('bank', 'Bank Account'), ('owner', 'Owner Equity'), ('suspense', 'Holding/Suspense')], default=None, max_length=8, null=True),
        ),
    ]
