# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 23:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentFinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_financial_year', models.CharField(choices=[('F18', (datetime.date(2017, 7, 1), datetime.date(2018, 6, 30))), ('F16', (datetime.date(2015, 7, 1), datetime.date(2016, 6, 30))), ('F17', (datetime.date(2016, 7, 1), datetime.date(2017, 6, 30))), ('F15', (datetime.date(2014, 7, 1), datetime.date(2015, 6, 30)))], max_length=3)),
            ],
        ),
    ]
