# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 05:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0002_auto_20170615_0855'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.IntegerField(default=14)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='entities.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='CreditorInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(null=True)),
                ('invoice_number', models.CharField(max_length=128)),
                ('order_number', models.CharField(blank=True, default='', max_length=128)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('gst_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.Creditor')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledgers.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=19, null=True)),
                ('creditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditors.Creditor')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledgers.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditorPaymentInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_paid', models.DecimalField(decimal_places=2, max_digits=19)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditors.CreditorInvoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditors.CreditorPayment')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ledgers.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
