# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=6)),
                ('bsb', models.CharField(blank=True, default='', max_length=64)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=2048)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to='ledgers.Account')),
            ],
        ),
    ]
