# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentFinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_financial_year', models.CharField(choices=[('F15', 'F15'), ('F16', 'F16'), ('F17', 'F17'), ('F18', 'F18')], max_length=3)),
            ],
        ),
    ]
